#!/usr/bin/env python3
"""
resolve_drive_ids.py — Fill in diagrams.drive_file_id from Google Drive

For each row in the `diagrams` table where drive_file_id IS NULL,
this script walks the Drive folder tree to find the file at drive_path
and updates the row with the real Google Drive fileId.

Usage:
    python resolve_drive_ids.py \\
        --key ../service-account.json \\
        --db-url "http://localhost:8787"   # Worker API base (or use D1 directly)

Or run directly against the D1 database file for local dev:
    python resolve_drive_ids.py --key service-account.json --local

Requirements:
    pip install google-auth requests

After running:
    The Worker's /images/:diagram_key endpoint will start serving images
    for any keys that now have a drive_file_id.
"""

import argparse
import json
import sys
from pathlib import Path

try:
    import requests
    from google.oauth2 import service_account
    from google.auth.transport.requests import Request as GoogleRequest
except ImportError:
    sys.exit("Missing dependencies: pip install google-auth requests")

DRIVE_SCOPES = ['https://www.googleapis.com/auth/drive.readonly']
DRIVE_FILES_URL = 'https://www.googleapis.com/drive/v3/files'


def get_credentials(key_path: Path):
    creds = service_account.Credentials.from_service_account_file(
        str(key_path), scopes=DRIVE_SCOPES
    )
    creds.refresh(GoogleRequest())
    return creds


def find_file_by_path(creds, drive_path: str) -> str | None:
    """
    Resolve a Drive-relative path like 'Diagrams/ChemistryU2/P2/2024/output/q1.png'
    to a Drive fileId by walking each folder component.

    Returns the fileId string, or None if not found.
    """
    parts = Path(drive_path.replace('\\', '/')).parts
    parent_id = 'root'

    for i, part in enumerate(parts):
        is_last = (i == len(parts) - 1)
        mime = None if is_last else 'application/vnd.google-apps.folder'

        params = {
            'q': (
                f"name = {json.dumps(part)} "
                f"and '{parent_id}' in parents "
                f"and trashed = false"
                + (f" and mimeType = '{mime}'" if mime else "")
            ),
            'fields': 'files(id, name)',
            'pageSize': 1,
        }
        headers = {'Authorization': f'Bearer {creds.token}'}
        resp = requests.get(DRIVE_FILES_URL, params=params, headers=headers, timeout=15)
        resp.raise_for_status()
        files = resp.json().get('files', [])
        if not files:
            return None
        parent_id = files[0]['id']

    return parent_id  # Last component's ID is the file ID


def main():
    parser = argparse.ArgumentParser(description='Fill drive_file_id for diagrams table')
    parser.add_argument('--key', required=True, help='Path to service account JSON key')
    parser.add_argument(
        '--diagrams-json', required=True,
        help='Path to a JSON file containing diagram rows: [{diagram_key, drive_path}]'
    )
    parser.add_argument(
        '--out', default='drive_id_updates.sql',
        help='Output SQL file with UPDATE statements'
    )
    args = parser.parse_args()

    key_path = Path(args.key)
    if not key_path.exists():
        sys.exit(f"Key file not found: {key_path}")

    diagrams_path = Path(args.diagrams_json)
    if not diagrams_path.exists():
        sys.exit(f"Diagrams JSON not found: {diagrams_path}")

    with open(diagrams_path, encoding='utf-8') as f:
        diagrams = json.load(f)

    print(f"Loaded {len(diagrams)} diagram rows.")
    print("Authenticating with Google Drive…")
    creds = get_credentials(key_path)
    print("Authenticated.")

    updates: list[str] = [
        "-- Auto-generated by resolve_drive_ids.py",
        "PRAGMA foreign_keys = ON;",
        "",
    ]
    resolved = 0
    not_found = 0

    for i, d in enumerate(diagrams, 1):
        key  = d['diagram_key']
        path = d['drive_path']
        print(f"  [{i}/{len(diagrams)}] {key}  →  {path}", end='  ', flush=True)

        # Refresh token if needed
        if not creds.valid:
            creds.refresh(GoogleRequest())

        file_id = find_file_by_path(creds, path)
        if file_id:
            escaped_key     = key.replace("'", "''")
            escaped_file_id = file_id.replace("'", "''")
            updates.append(
                f"UPDATE diagrams SET drive_file_id = '{escaped_file_id}', "
                f"last_synced_at = datetime('now') "
                f"WHERE diagram_key = '{escaped_key}';"
            )
            print(f"✓ {file_id}")
            resolved += 1
        else:
            print("✗ not found in Drive")
            not_found += 1

    out_path = Path(args.out)
    out_path.write_text('\n'.join(updates), encoding='utf-8')

    print(f"\n{'='*60}")
    print(f"Resolved : {resolved}")
    print(f"Not found: {not_found}")
    print(f"Output   : {out_path}")
    print(f"{'='*60}")
    print("\nLoad into D1:")
    print("  wrangler d1 execute cape-questions --local --file=drive_id_updates.sql")
    print("  wrangler d1 execute cape-questions --file=drive_id_updates.sql")


if __name__ == '__main__':
    main()
